config/routes.rb
Rails.application.routes.draw do
  get '/rails/info/routes' => 'routes'
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  resources :movies do
    resources :reviews, shallow: true
  end
  resources :users, :only => [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  columns = [:plot_rating, :acting_rating, :screenplay_rating, :cinematography_rating,
             :musical_score_rating, :editing_rating, :directing_rating]

  columns.each do |column|
    validates column, presence: true
  end

end

app/models/user.rb
class User < ApplicationRecord

  #TODO I was thinking of removing the feature of a user being able to add a movie
  #TODO and just have a rotten tomatos api prepopulate the database with movies.

  has_many :movies
  has_many :reviews, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :username, presence: true, length: { maximum: 50 }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name
      #user.image = auth.info.image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

    def after_sign_in_path_for(user)
      movies_url
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :edit, :destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
    @genre_options = Genre.all.map { |g| [g.name, g.id] }
  end

  def create
    @movie = current_user.movies.build(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render "new"
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews
  end

  private

    def movie_params
      params.require(:movie).permit(:title, :description, :genre_id)
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:username,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:username,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :current_password)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :edit, :destroy]

  def new
    @review = Review.new
    @movie  = Movie.find(params[:movie_id])
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.movie_id = params[:movie_id]
    @movie = Movie.find(@review.movie_id)

    if @review.save
      redirect_to @movie
    else
      render "new"
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

    def review_params
      params.require(:review).permit(:user_id, :movie_id, :plot_rating, :acting_rating,
                                     :screenplay_rating, :cinematography_rating, :musical_score_rating,
                                     :editing_rating, :directing_rating, :average_rating, :opinion)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def home

  end

  def about

  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end
end

app/helpers/application_helper.rb
require "movies_helper.rb"
require "reviews_helper.rb"

module ApplicationHelper
  include MoviesHelper
  include ReviewsHelper

  def gravatar_for(email, size=200)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def create_account_section_partial_path
    if !user_signed_in?
      "layouts/create_account_section/display_block"
    else
      "layouts/create_account_section/display_none"
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def review_card_star_rating_partial_path(i, review)
    if i < review.average_rating
      "shared/cards/card/star-on.html.erb"
    else
      "shared/cards/card/star-off.html.erb"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="container">
    <small class="copyright text-center">&copy<%= Time.now.year %> Simple Critic</small>
  </div>
</footer>

app/views/layouts/_head_links.html.erb
<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': 'false' %>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<div class="container">
  <nav class="navbar navbar-expand-lg">
    <%= link_to image_tag("logo.svg", class: "logo"), root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <i class="fa fa-bars fa-2x" aria-hidden="true"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Movies", movies_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
            Account
          </a>

          <div class="col-sm-5 m-auto dropdown-menu text-center">
            <% if user_signed_in? %>
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/head_links' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <!--
    <% flash.each do |msg_type, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
    <% end %>
    -->
    <div class="container">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

    <!--<%= debug(params) if Rails.env.development? %>-->

  </body>
</html>

app/views/layouts/create_account_section/_display_block.html.erb
<div class="row d-block">
  <div class="col bottom-signup">
    <h3>Create an account to</br>start reviewing movies!</h3>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-outline-light hero-btn" %>
  </div>
</div>

app/views/layouts/create_account_section/_display_none.html.erb
<div class="row d-none">
  <div class="col bottom-signup">
    <h3>Create an account to</br>start reviewing movies!</h3>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-outline-light hero-btn" %>
  </div>
</div>

app/views/movies/_movie_info.html.erb
<div class="row">
  <div class="col-md-9 m-auto">
    <div class="movie-info text-center pb-5">
      <%= image_tag("https://upload.wikimedia.org/wikipedia/en/a/a6/The_Thing_%281982%29_theatrical_poster.jpg",
                    class: "mb-3") %>
      <h1 class="mb-3"><%= movie.title %></h1>
      <p class="mb-3"><%= movie.description %></p>
      <p class="mb-3"><%= movie.genre.name %></p>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<% provide(:title, "Movies") %>

<%= link_to "Add Movie", new_movie_path, class: "btn btn-lg review-btn mb-5 mt-3" %>

<div class="movies">
  <% @movies.each do |movie| %>
    <%= link_to movie, class: "thumbnail" do %>
      <%= image_tag("https://vignette.wikia.nocookie.net/my-miis/images/a/a5/X.png/revision/latest?cb=20180213211539", class: "img-thumbnail") %>
      <h2 class="title mb-5"><%= truncate(movie.title, :length => 20) %></h2>
    <% end %>
  <% end %>
</div>

<%= render create_account_section_partial_path %>

app/views/movies/new.html.erb
<h1 class="text-center mb-5">Add a</br>movie</h1>

<div class="row">
  <div class="col-sm-8 col-lg-6 m-auto">
    <%= bootstrap_form_for(@movie) do |f| %>
      <%= f.text_field :title%>
      <%= f.text_area :description%>
      <%= f.select(:genre_id, @genre_options) %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<%= render "movies/movie_info", movie: @movie %>

<%= link_to "Add Review", new_movie_review_path(@movie), class: "btn btn-lg review-btn mb-5 mt-5" %>

<% @reviews.each do |review| %>
  <%= render "shared/cards/review_card", review: review %>
<% end %>

app/views/reviews/_ratings_form.html.erb
<div class="rating-form">
  <div class="plot" data-star="rateable">
    <lable>Plot</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="acting" data-star="rateable">
    <lable>Acting</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="screenplay" data-star="rateable">
    <lable>Screenplay</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="cinematography" data-star="rateable">
    <lable>Cinematography</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="musical_score" data-star="rateable">
    <lable>Musical Score</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="editing" data-star="rateable">
    <lable>Editing</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="directing" data-star="rateable">
    <lable>Directing</label>
    <%= render "reviews/stars" %>
  </div>

  <div class="average d-none" id="average">
    <lable>Average</label>
    <%= render "reviews/stars" %>
  </div>
</div>

app/views/reviews/_stars.html.erb
<div class="stars">
  <% (1..5).each do |num| %>
    <%= image_tag "star-off", class: "star", data: { state: "off" } %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-sm-8 col-lg-6 m-auto">
    <%= bootstrap_form_for [@movie, @review], url: movie_reviews_path do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= render "reviews/ratings_form" %>
      <%= f.hidden_field :plot_rating %>
      <%= f.hidden_field :acting_rating %>
      <%= f.hidden_field :screenplay_rating %>
      <%= f.hidden_field :cinematography_rating %>
      <%= f.hidden_field :musical_score_rating %>
      <%= f.hidden_field :editing_rating %>
      <%= f.hidden_field :directing_rating %>
      <%= f.hidden_field :average_rating %>
      <%= f.text_area :opinion %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<%= @review.movie.title %></br>
<%= @review.opinion %></br>
<%= @review.user.username %></br>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <p>This form contains <%= pluralize(object.errors.count, "error") %>:</p>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    <ul>
  </div>
<% end %>

app/views/shared/cards/_review_card.html.erb
<div class="card col-sm-12 col-md-9 col-lg-7">
  <div class="card-heading mt-3">
    <%= render "shared/cards/card/heading", review: review %>
  </div>

  <div class="card-body text-center">
    <%= render "shared/cards/card/body", review: review %>
  </div>
</div>

app/views/shared/cards/card/_body.html.erb
<h2><%= review.movie.title %></h2>
<p><%= review.opinion %></p>

<%= link_to "Read Full Review", review %>

app/views/shared/cards/card/_heading.html.erb
<!--<%= image_tag gravatar_for(review.user.email) %>-->
<div class="card-user-info float-left">
  <%= image_tag("https://upload.wikimedia.org/wikipedia/en/a/a6/The_Thing_%281982%29_theatrical_poster.jpg",
                 class: "card-user-img") %>
  <h3><%= review.user.username %></h3>
  <p>22 minutes ago</p>
</div>

<div class="float-right text-right">
  <!--<h5 class="card-stars">Review Stars</h5> -->
  <ul>
    <% 5.times do |i| %>
      <%= render review_card_star_rating_partial_path(i, review) %>
    <% end %>
  </ul>
  <button class="btn btn-follow">Follow</button>
</div>

app/views/shared/cards/card/_star-off.html.erb
<li><%= image_tag "star-off", class: "star" %></li>

app/views/shared/cards/card/_star-on.html.erb
<li><%= image_tag "star-on", class: "star" %></li>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
  <h1>A platform for movie</br>lovers to share their</br>thoughts</h1>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-outline-light hero-btn" %>
</div>

<div class="row">
  <div class="col-12-sm col-md-6 col-lg-4">
    <div class="card mb-4">
      <div class="card-body text-center">
        <i class="fas fa-book-open fa-3x"></i>
        <h5 class="card-title">Read Movie Reviews</h5>
        <p class="card-text">Lorem ipsum dolor amet salvia you probably
          haven't heard of them craft beer hell of letterpress
          venmo ethical small batch etsy lumbersexual gastropub
        </p>
      </div>
    </div>
  </div>

  <div class="col-12-sm col-md-6 col-lg-4">
    <div class="card mb-4">
      <div class="card-body text-center">
        <i class="fas fa-pencil-alt fa-3x"></i>
        <h5 class="card-title">Write Your Own Reviews</h5>
        <p class="card-text">Lorem ipsum dolor amet salvia you probably
          haven't heard of them craft beer hell of letterpress
          venmo ethical small batch etsy lumbersexual gastropub
        </p>
      </div>
    </div>
  </div>

  <div class="col-12-sm col-md-12 col-lg-4">
    <div class="card mb-4">
      <div class="card-body text-center">
        <i class="fas fa-hands-helping fa-3x"></i>
        <h5 class="card-title">Stay Connected</h5>
        <p class="card-text">Lorem ipsum dolor amet salvia you probably
          haven't heard of them craft beer hell of letterpress
          venmo ethical small batch etsy lumbersexual gastropub
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col bottom-signup">
    <h3>Start reviewing movies for free!</h3>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-outline-light hero-btn" %>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="user-info pb-5 mb-5">
  <section class="info">
    <%= render "users/info/bio", user: @user %>
  </section>

  <section class="stats text-center">
    <div class="row">
      <%= render "users/info/stats", user: @user %>
    </div>
  </section>
</div>

app/views/users/info/_bio.html.erb
<%= image_tag gravatar_for(user.email), alt: "User Image", class: "user-logo mt-5" %>

<h1 class="text-center mt-4"><%= user.username %><h1>

<p class="col-sm-8 text-center mt-4 mx-auto">Lorem ipsum dolor amet dIY hammock woke thundercats meggings mixtape vice occupy</p>

app/views/users/info/_stats.html.erb
<a href="#" class="stat mt-4 col-sm-4">
  Following </br>
  <span class="count">50</span>
</a>

<a href="#" class="stat mt-4 col-sm-4">
  Following </br>
  <span class="count">50</span>
</a>

<a href="#" class="stat mt-4 col-sm-4">
  Reviews </br>
  <span class="count">50</span>
</a>

app/views/users/show.html.erb
<%= render "users/user_info" %>

<div class="row">
  <% @reviews.each do |review| %>
    <%= render "shared/cards/review_card", review: review %>
  <% end %>
</div>